version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./containers/backend.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    working_dir: /app/

  telegram-bot:
    container_name: telegram-bot
    depends_on:
      - web
    build:
      context: .
      dockerfile: ./containers/backend.Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env
    command: >
      sh -c "python manage.py run_bot"
