version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: ./containers/backend.Dockerfile
    command: /bin/sh -c "./scripts/run_server.sh"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    working_dir: /app/

  telegram-bot:
    container_name: telegram-bot
    depends_on:
      - server
    build:
      context: .
      dockerfile: ./containers/backend.Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - backend/.env
    command: /bin/sh -c "./scripts/run_telegram_bot.sh"
