version: '3.8'

services:
  telegram-bot:
    build:
      context: ./
      dockerfile: ./containers/bot/Dockerfile
    env_file:
      - .env
    command: >
      sh -c "cd ./bot &&
            python bot.py"
