# Generated by Django 5.1.1 on 2024-09-11 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("telegram_bot", "0002_message_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "date_time",
                    models.DateTimeField(verbose_name="Date and time to remind"),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[("meeting", "Meeting"), ("other", "Other")],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        max_length=36, null=True, verbose_name="Delayed task ID (UUID)"
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="telegram_bot.tgchat",
                    ),
                ),
            ],
        ),
    ]
