# Generated by Django 5.1.1 on 2024-10-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reminder", "0002_reminder_user_specified_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="reminder",
            name="text_original",
            field=models.TextField(default=""),
        ),
    ]
