# Generated by Django 4.1.9 on 2024-03-31 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgChat',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TgMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
                ('message', models.TextField()),
                ('user_id', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('tg_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.tgchat')),
            ],
        ),
    ]
