# Generated by Django 5.1.1 on 2024-09-10 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgChat',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('region', models.CharField(max_length=100, null=True, verbose_name='Country or city user lives in')),
                ('language', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('user_id', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TgMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('message_from', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=50)),
                ('tg_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.tgchat')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
