# Generated by Django 5.1.1 on 2024-09-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0002_message_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tgmessage",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
