# Generated by Django 5.1.1 on 2024-09-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0003_alter_tgmessage_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tgchat",
            name="region",
            field=models.CharField(
                max_length=100,
                null=True,
                verbose_name="Country or city user lives in + timezone",
            ),
        ),
    ]
